### PR TITLE
Fix for Scheduler "Task Already Running" Bug

### LINKED ISSUE #352: Scheduler bug: Cannot get next task, a task is already running
The previous run ended with a recursion limit error, leaving the last task in the `processing` state, so when next run attempts to start we get the following error:
```
2025-03-19 11:22:04.456 | INFO    | [task-scheduler] | Cannot get next task, a task is already running in namespace: orchestrator
{
  runningTaskId: '0451a20b-1bbe-47c6-a530-31455acec6a4'
}
2025-03-19 11:22:04.557 | INFO    | [task-scheduler] | Cannot get next task, a task is already running in namespace: orchestrator
{
  runningTaskId: '0451a20b-1bbe-47c6-a530-31455acec6a4'
}
```

### PR DESCRIPTION
**Pull request by Xm0onh**
## Issue Reference
This PR resolves #352  - "Scheduler bug: Cannot get next task, a task is already running"

## Problem
When a task encounters a recursion limit error, it can get stuck in the "processing" state. This causes subsequent attempts to run new tasks to fail with:
```
Cannot get next task, a task is already running in namespace: orchestrator
```

This leaves the orchestrator in an inconsistent state requiring manual intervention to fix.

### 1. Improved Error Handling
- Restructured try/catch blocks in the task executor to properly detect and handle recursion limit errors
- Added specific handling for recursion limit errors that automatically marks failed tasks appropriately
```ts
if (error instanceof Error && error.message.includes('Recursion limit') && dueTask) {
  runner.updateTaskStatus(dueTask.id, 'failed', error.message);
}
```

### 2. Task Status Management Enhancements
- Exposed `updateTaskStatus` method in the `OrchestratorRunner` interface to allow external components to update task statuses directly
- Modified `getNextDueTask` to return the currently running task instead of undefined when checking for due tasks
- Improved task result handling by storing the summary string directly rather than a nested object
- Replaced generic `any` result type with specific `string` type for task results

### CODE REVIEW

File: src/agents/workflows/orchestrator/scheduler/taskExecutor.ts [hunk 1]
```diff
@@ -40,6 +40,9 @@ export const startTaskExecutor = (
       logger.error('Error executing scheduled task', {
         error: error instanceof Error ? error.message : String(error),
       });
+      if (error instanceof Error && error.message.includes('Recursion limit') && dueTask) {
```
Comment (jfrank-summit) [inline src/agents/workflows/orchestrator/scheduler/taskExecutor.ts:43]: Why only if it is a recursion limit error? Shouldn't we set to `failed` on any failure?

**Review by jfrank-summit — APPROVED** [review]
LGTM
